#!/usr/bin/env bash
# Turn Terraform outputs into Helm values for the cloudsmith-registry chart.
# This is the bridge that makes "Terraform outputs == helmfile inputs" — there
# are NO hardcoded org/repo/service slugs in the wired pipeline.
#
# Usage: ./scripts/tf-to-values.sh [output-file]
#   default output: ./chart-values.generated.yaml (git-ignored)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/chart-values.generated.yaml}"

cd "$ROOT/terraform"

ORG="$(terraform output -raw org_slug)"
REPO="$(terraform output -raw repository_slug)"
SVC="$(terraform output -raw shared_service_slug)"

if [[ -z "$ORG" || -z "$REPO" || -z "$SVC" ]]; then
  echo "ERROR: terraform outputs are empty — run 'terraform apply' first." >&2
  exit 1
fi

cat > "$OUT" <<EOF
# AUTO-GENERATED by scripts/tf-to-values.sh from 'terraform output'.
# Do not edit; not committed (see .gitignore).
cloudsmith:
  org: "${ORG}"
  repo: "${REPO}"
  serviceSlug: "${SVC}"
EOF

echo "Wrote $OUT:"
echo "  org=$ORG repo=$REPO serviceSlug=$SVC"
